"use strict";
let places = ["Lake Saif ul Maluk", "Turkey", "Makkah", "Madina", "Paris"];
console.log("Original order:");
console.log(places);
console.log("Alphabetical order:");
console.log(places.slice().sort());
console.log("Original order:");
console.log(places);
console.log("Reverse alphabetical order:");
console.log(places.slice().sort().reverse());
console.log("Original order:");
console.log(places);
console.log("Its order has changed");
console.log(places.slice().reverse());
console.log("It's back to its original order!");
console.log(places.slice().reverse().reverse());
places.sort();
console.log("Its order has been changed!");
console.log(places);
places.reverse();
console.log("Reverse alphabetical order:");
console.log(places);
